# Generated by Django 5.2.6 on 2025-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Required a valid email.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
